<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>netstandard2.0;net8.0</TargetFrameworks>
    <RootNamespace>Seashyne.Core</RootNamespace>
    <AssemblyName>Seashyne.Core</AssemblyName>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <Authors>Seashyne</Authors>
    <Description>Universal cross-project utility library for C# (Unity, Godot, and .NET)</Description>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <RepositoryUrl>https://github.com/seashyne/Libraries</RepositoryUrl>
  </PropertyGroup>

</Project>
